### ISSUE TITLE
Sharing Doesn't Copy

### ISSUE THREAD

**Issue by josolanes** [modem7/react-wordle#14] opened 2022-03-17 13:33 UTC
I updated earlier this morning with the latest tag and sharing seems to have stopped working. Clicking the Share button after completing it no longer copies anything to the clipboard.

I saw in the other issue you referenced https://reactle.vercel.app/ so I tried to reproduce it, but sharing copies the results as expected there.

Thank you for your work on this!

EDIT:
I've confirmed this on Android Chrome, Windows Chrome, and Linux Chrome

**Comment by modem7** [comment] 2022-03-17 14:21
No worries!

What I'm looking to do, is recreate the entire project from scratch and recreating the image from upstream.

Might take until the weekend depending how work goes, but bear with me and I'll get on it!

In the meantime, there's a legacy tag which is the old version that's unmodified.

**Comment by josolanes** [comment] 2022-03-17 14:28
Excellent thank you so much @modem7 !

**Comment by modem7** [comment] 2022-03-18 16:22
Just an update, it looks like the upstream may also be having this issue. 

I've submitted an issue and hopefully we'll get it resolved relatively quickly. 

Good to know it wasn't (just) something I did! :P

If you wish, you can test this yourself by doing:

```bash
git clone https://github.com/cwackerfuss/react-wordle.git &&
cd react-wordle/ &&
docker build --no-cache --target=prod -t wordle:test -f docker/Dockerfile . &&
docker run -d -p 80:8080 --name reactle-prod wordle:test &&
cd ../ && rm -rf ./react-wordle
```

Open browser to serverIP:80

Then when you're done

```bash
docker container stop reactle-prod; docker container rm reactle-prod; docker image prune -af
```

**Comment by modem7** [comment] 2022-03-20 14:16
@josolanes Turns out this is an intentional functionality from browsers when a site isn't hosted via https. 

https://github.com/cwackerfuss/react-wordle/issues/331#issuecomment-1073155476

If you host it via https instead of local, the functionality works as intended. 

This is how I tested:

```yaml
  wordle:
    image: modem7/wordle
    container_name: Wordle
    ports:
      - 80:8080
    networks:
      pihole:
    labels: 
      # - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.wordletest-rtr.entrypoints=https"
      - "traefik.http.routers.wordletest-rtr.rule=Host(`wordletest.$DOMAINNAME`)"
      - "traefik.http.routers.wordletest-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.wordletest-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.wordletest-rtr.service=wordletest-svc"
      - "traefik.http.services.wordletest-svc.loadbalancer.server.port=8080"
```

Could you confirm that works on your end and then we can look at closing the issue if so.

**Comment by josolanes** [comment] 2022-03-20 14:30
Ah! That's likely it, mine is http not https

I'll try to move it over to https later and will let you know. Thank you so much for looking into it and finding this!

**Comment by modem7** [comment] 2022-03-20 14:32
> Ah! That's likely it, mine is http not https
> 
> I'll try to move it over to https later and will let you know. Thank you so much for looking into it and finding this!

No worries! I'm glad it got found out by another user! 

I'll keep this open until you tested and hopefully it all works as intended!

**Comment by josolanes** [comment] 2022-03-20 19:30
Hi @modem7 I feel like due to intricacies in my system (hosting several sites, some in VM, some in docker) that I'm unable to make wordle use https. I'm also not super strong with networking and setup, but have enough knowledge to setup some things

Consequently, I'm working on moving over to the legacy tag but that keeps giving me a 500 when trying to create it (using portainer as a docker UI). I can't seem to figure out how to get additional details except a 500 occurs. I am able to pull the image, but unable to create the container with basic setup (80:80 port is basically it)

**Comment by modem7** [comment] 2022-03-20 19:46
> Hi @modem7 I feel like due to intricacies in my system (hosting several sites, some in VM, some in docker) that I'm unable to make wordle use https. I'm also not super strong with networking and setup, but have enough knowledge to setup some things
> 
> Consequently, I'm working on moving over to the legacy tag but that keeps giving me a 500 when trying to create it (using portainer as a docker UI). I can't seem to figure out how to get additional details except a 500 occurs. I am able to pull the image, but unable to create the container with basic setup (80:80 port is basically it)

Heya,

I'm just sorting some stuff out, but are you able to give me a shout on discord at modem7#1136 and we'll see if we can get things resolved for you.

**Comment by modem7** [comment] 2022-03-20 21:17
Resolved via discussion on discord and recreating container using a different external port.

**Closed as completed** 2022-03-20 21:17 UTC
Labels: bug, good first issue

**Comment by modem7** [comment] 2022-03-24 01:02
Just as an FYI for anyone looking at this issue. 

Sharing has been resolved. The issue was due to not hosting as HTTPS as per https://github.com/modem7/react-wordle/issues/14#issuecomment-1073261043.
