### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by Phaeton** [modem7/react-wordle#13] opened 2022-03-17 01:55 UTC
With the updated look, I’m seeing some scaling issues on an iPhone 8. The letter boxes are huge in comparison to before and the keyboard is partially off the bottom of the screen, requiring you to scroll down to see it completely. Everything fit nicely on the screen before.

**Comment by modem7** [comment] 2022-03-17 02:22
Heya, 

Thanks for the report. 

Unfortunately I've just forked it from https://github.com/cwackerfuss/react-wordle/ and edited a few things, mostly in the dockerfile + github pages.

Do you get the same problem here? https://reactle.vercel.app

If so, I'd recommend creating an [issue](https://github.com/cwackerfuss/react-wordle/issues/new?assignees=&labels=&template=bug_report.md&title=) at the original developer, and I can get it ported over once the issue is resolved. 

However, in the meantime, I've re-created the older version for you. 

```yaml
  wordle:
    image: modem7/wordle:legacy
    container_name: Wordle
    ports:
      - 80:80
```

Hope that helps in the meantime!

**Comment by Phaeton** [comment] 2022-03-17 10:36
Yes, I have the same issue at https://reactle.vercel.app/. Appreciate the Legacy build to deal with the WAF.

**Comment by modem7** [comment] 2022-03-17 16:06
Looks like it's being dealt with [here](https://github.com/cwackerfuss/react-wordle/issues/314) and [here](https://github.com/cwackerfuss/react-wordle/pull/294).

I'll close this issue for now and follow the upstream.

**Closed as completed by modem7** 2022-03-17 16:06 UTC
Labels: bug, help wanted, good first issue

**Comment by trashken** [comment] 2022-08-31 03:56
Hi! https://reactle.vercel.app/ doesn't have this issue anymore but still persists in this fork. Any ideas?

**Comment by modem7** [comment] 2022-08-31 11:41
> Hi! https://reactle.vercel.app/ doesn't have this issue anymore but still persists in this fork. Any ideas?

Aye,

I'll need to merge the changes at some point.

If I get some time this weekend I'll get it sorted!
